### ISSUE TITLE
Caching of decompressed assets for lowest latency reading

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#103]
Building on https://github.com/pyros2097/rust-embed/issues/90:
A common use case of rust-embed is web servers (e.g. desktop apps that embed a web server to render their UI in a browser view). 
For web servers or anything that needs to read the embedded files as fast as possible and multiple times over the lifetime of the process, it makes sense to decompress each asset only once and then cache the result, so that further calls for the same path can return the cached/decompressed value immediately.
This could be another feature, e.g. `cached-compression` which also enables the `compression` feature when it is enabled.
For the memoization/caching of each asset we could use [`OnceCell`/`Lazy`](https://docs.rs/once_cell/1.3.1/once_cell/#general-purpose-lazy-evaluation) (or an `Option`).

@Mcat12 What do you think? :)

**Comment by Boscop** [comment]
Ah nvm, it already only decompresses the first time..

**Comment by kovalensky** [comment]
Where does it decompress the files?
Also is it possible to choose a different algorithm, like lzma?

**Comment by kovalensky** [comment]
Understood, by once he meant lazy dispatch.

I used lzma_rs crate to embed compressed data into binary as a workaround 👍🏻
