### ISSUE TITLE
Question: How does the library write out the extra messages during compile

### ISSUE THREAD

**Issue by DusterTheFirst** [pyros2097/rust-embed#105]
From the image in the documentation, 
![image](https://user-images.githubusercontent.com/14093962/78101863-cd126b80-73b6-11ea-9cb1-0c73a78e752d.png)

The library seems to add its own output on to the output of cargo which looks really nice and i was wondering how this was achieved

**Comment by pyros2097** [comment]
Thats pretty simple. We had that outputting in v2.0.0 but removed it for some reason. Here's the code.
https://github.com/pyros2097/rust-embed/blob/6d727a85aab19b958e7c4a41b7a551ed0386222a/src/lib.rs#L58

**Comment by DusterTheFirst** [comment]
Ah, good to know. Thanks!
