### ISSUE TITLE
Can I get the separate files after embedding them

### ISSUE THREAD

**Issue by hyousef-rusty** [pyros2097/rust-embed#110]
After building the `.exe` file, assume I want to extract/get the JS file I used, is there a way to extract it back?

i tried in Windows changing the extension from `.exe` to `.zip` but could not extract the generated file, i know some applications use this trip but did not work with me!

![image](https://user-images.githubusercontent.com/60115476/82698552-a284b680-9c73-11ea-869f-925afe713580.png)

**Comment by Mcat12** [comment]
The files are embedded into the executable binary as raw data. An executable file is not a zip file, and the only supported method of retrieving the file data is by using the API that rust-embed provides. You can add some functionality to your application to export the embedded files by iterating over the files ([`iter`]), retrieving their data ([`get`]), and writing them out to the filesystem.

[`iter`]: https://docs.rs/rust-embed/5.5.1/rust_embed/trait.RustEmbed.html#tymethod.iter
[`get`]: https://docs.rs/rust-embed/5.5.1/rust_embed/trait.RustEmbed.html#tymethod.get
