### ISSUE TITLE
Windows path release build `\` should be `/`

### ISSUE THREAD

**Issue by ralpha** [pyros2097/rust-embed#115]
I noticed that subpaths on my Rocket projects that uses similar code to https://github.com/pyros2097/rust-embed/blob/master/examples/rocket.rs did not work on windows in release build (when files get embedded).

I fixed this by changing:
https://github.com/pyros2097/rust-embed/blob/3b1ac9f4d671af9cf2aa87a8cfd7f76dfa9b7641/examples/rocket.rs#L27
to
```rust
let filename = file.display().to_string().replace("\\", "/");
```
It now works on linux and windows in both release builds.

I also found [this issue](https://github.com/pyros2097/rust-embed/issues/36) which looked similar but PR did not seem to solve this.

**Comment by pyros2097** [comment]
@ralpha if everything works fine and tests pass then raise a PR will merge the change.

**Comment by Mcat12** [comment]
Maybe we should consider changing the API to take in `Path` instead of `&str`.

**Comment by pyros2097** [comment]
@Mcat12 that seems better. Thet way we won't have these path issues across various platforms.
