### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by ralpha** [pyros2097/rust-embed#124]
`rust-embed` does not seem to use unsafe code, which is very good :)

To prevent this from ever happening, add following line to the top:
```rust
#![forbid(unsafe_code)]
```
of https://github.com/pyros2097/rust-embed/blob/master/src/lib.rs
and https://github.com/pyros2097/rust-embed/blob/master/utils/src/lib.rs
and https://github.com/pyros2097/rust-embed/blob/master/impl/src/lib.rs

This will make the package green in 
https://github.com/rust-secure-code/cargo-geiger

**Comment by pyros2097** [comment]
@ralpha a PR would be nice.

**Comment by billyb2** [comment]
I apologize, but do you think this issue can be closed? I think the PR adds everything @ralpha wanted

**Comment by pyros2097** [comment]
@billyb2 yes this can be closed now.

**Comment by ralpha** [comment]
Thanks @billyb2 for making the PR and adding this :)
