### ISSUE TITLE
Incorrect use of `syn` dependency in `rust-embed-impl`

### ISSUE THREAD

**Issue by TrevorAC99** [pyros2097/rust-embed#127]
Line 8 of https://github.com/pyros2097/rust-embed/blob/245398a6f255642290585e63d50cbedd229508b3/impl/src/lib.rs#L8 has `use syn::{export::TokenStream2, Data, DeriveInput, Fields, Lit, Meta};` which is now invalid in the latest release of syn. Specifically, `export::TokenStream2` is apparently a private implementation detail and shouldn't be used. See https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7 for more details. A temporary solution would be to pin `syn` to version 1.0.57 since version 1.0.58 is the one that caused the problem.

**Comment by pyros2097** [comment]
@TrevorAC99 Thanks for finding this out.
