### ISSUE TITLE
Broken crate due to Syn changes

### ISSUE THREAD

**Issue by woodruffw** [pyros2097/rust-embed#131]
Hey there!

I noticed that builds of `rust-embed-impl` are currently broken on `syn` `1.0.58` and newer -- those versions remove the `syn::export` module, since they were never intended to be a public interface. It looks like `rust-embed-impl` used that for `export::TokenStream2`, which should probably just be imported from `proc_macro2` instead:

```rust
use proc_macro2::TokenStream as TokenStream2;
```

I'd argue that that was technically a SemVer breakage (since it removed a public API, even if it was an unintentional one), on Syn's part, but in any case the error is manifesting here.

**Comment by woodruffw** [comment]
Whoops, this was already addressed. Sorry for the overeager report!

**Comment by Mcat12** [comment]
Even though it's already addressed, thanks for taking the time to report it!
