### ISSUE TITLE
Allow leading slash in path names

### ISSUE THREAD

**Issue by WesleyAC** [pyros2097/rust-embed#132]
I have paths in the form of `/some/file` that I want to serve out of RustEmbed. I think that this should be supported, to save me the work of snipping the paths myself.

I see three ways to go about this:

* `/some/path` and `some/path` are treated identically. `some/path` is still the canonical name. This seems like not an ideal solution, for several reasons.
* Add a attribute to the `RustEmbed` macro to toggle leading slashes.
* Add an attribute to the `RustEmbed` macro to enable arbitrary prefixes.

I think the third option is best, but would be happy enough with any of them.

Would you take a PR that implemented this?

**Comment by Mcat12** [comment]
What is the difference between an arbitrary prefix and a leading slash?

The workaround for this seems to be pretty easy on the application side (just call [`trim_start_matches`] or [`strip_prefix`]), so I'm not sure if it's correct to move that application-specific prefix behavior to the library.

[`trim_start_matches`]: https://doc.rust-lang.org/stable/std/primitive.str.html#method.trim_start_matches
[`strip_prefix`]: https://doc.rust-lang.org/stable/std/primitive.str.html#method.strip_prefix

**Comment by WesleyAC** [comment]
I'm using `trim_start_matches` right now, but that has the disadvantage that `/foo` is treated the same way as `/////foo`, etc. I could see security problems coming from this approach — for instance, if a webserver requires a password to access `/foo`, but the check for that doesn't catch `//foo`. `strip_prefix` avoids this problem, but it requires handling the case where there is no prefix specially.

I don't think that this is a big problem, it just seems like something that it would be nice to handle in rust-embed, since there isn't a library function that does exactly the right thing, and it is presumably faster to not have to munge the string before passing it to rust-embed.

An arbitrary prefix would look like:

```rust
#[derive(RustEmbed)]
#[folder = "examples/public/", prefix = "/static/"]
struct Asset;
```

I don't think that this is that important of a usecase — it's not hard to just check the prefix and strip it if it's incorrect — but it seems about as easy to implement as allowing a `/` as a prefix, and it seems like it could be useful.

**Comment by Mcat12** [comment]
I think this isn't too hard to add, I'll look into it.
