### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by fhoehle** [pyros2097/rust-embed#135]
For packaging of downstream packages it would be nice to have a dedicated license which is used to gather all licenses of all depencies and repackage these license files.

**Comment by AzureMarker** [comment]
We have a license file in our repository for our code, are you asking for us to include the licenses of every one of our dependencies? Can you give an example of a Rust crate which does this? I've never seen this done; it seems like an odd request.

**Comment by fhoehle** [comment]
Sorry I oversaw the existing license file. It would ease detecting and gathering licenses of packages and their dependencies when your crate contains/ships its dependency. Here a PR proposing to add the existing license file: https://github.com/pyros2097/rust-embed/pull/136

**Comment by AzureMarker** [comment]
Ok, adding a reference to the license file in Cargo.toml is fine, thanks for clarifying.

**Comment by AzureMarker** [comment]
Reopening this, cargo warns that the `license-file` field is unnecessary:
```
warning: /home/mark/Projects/CLionProjects/rust-embed/Cargo.toml: only one of `license` or `license-file` is necessary
```

I propose that we remove it and keep the `license` field only. This seems to match crates.io expectations: 
> If a package is using a nonstandard license, then the license-file field may be specified in lieu of the license field.
- https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

**Comment by pyros2097** [comment]
Yep that seems good. Its better to use the `license` key.
