### ISSUE TITLE
Question on embedded files

### ISSUE THREAD

**Issue by ryancinsight** [pyros2097/rust-embed#138]
Can this be used to embed dll files and if yes will they automatically be loaded at run time similar to html example?

**Comment by AzureMarker** [comment]
rust-embed simply embeds your files in the binary as raw data. It doesn't do anything particularly intelligent beyond (optionally) compressing it.

**Comment by ryancinsight** [comment]
@AzureMarker Not looking for anything fancy or to be executed, basically I have a few dll's in a folder and next to exe that will be called upon by the exe. They should just work as long as they are present therefore I'm kind of curious if this would still work if embed and then all iterated over and opened from the wrapped exe and files before running the actual program. Currently, I'm creating an exe with program and dll folder zipped together with zstandard and exported to a hidden folder during its first run and symbolically run from there

**Comment by pyros2097** [comment]
I'm guessing you still have to iterate over the files from rust embed and write them to a hidden folder and then execute them. The dll's will be only useful as bytes and nothing more fancier than that. You still need to write them to the filesystem to be of any use. Rust embed does not implement something like a virtual file system.

**Comment by ryancinsight** [comment]
Thanks for the answers! Based on this, just curious if have you done any tests to see if it's faster to create a struct and compress/embed iteratively over a folder like your examples vs creating a tar file and compressing/embedding the entire tar folder?

**Comment by ryancinsight** [comment]
> I'm guessing you still have to iterate over the files from rust embed and write them to a hidden folder and then execute them. The dll's will be only useful as bytes and nothing more fancier than that. You still need to write them to the filesystem to be of any use. Rust embed does not implement something like a virtual file system.

I was actually thinking of this in terms of an injector, would be interesting if could be used like manual mapping to load a dll byte array without touching memory

**Comment by pyros2097** [comment]
> Thanks for the answers! Is there a put or place command that i'm missing than, not sure I see what you are doing with the embedded files once embedded? Are they being exported when run?

The embedded files are stored as u8 array data indexed by filepath. This is mainly used for stuff like web servers to send the html, js, css and jpg data directly from memory instead of reading the files first from the filesystem. It's easier to package and distribute such applications as a separate executable without packaging the data assets with it.

> Furthermore, just curious if have you done any tests to see if it's faster to create a struct and compress/embed iteratively over a folder like your examples vs creating a tar file and compressing/embedding the entire tar folder?

Haven't done this though. Don't think it will make much of a difference.
