### ISSUE TITLE
Create a Changelog

### ISSUE THREAD

**Issue by Mcat12** [pyros2097/rust-embed#14]
I haven't found any place which documents the changes in each version, so I assume the changes have never been documented besides the commit messages. It would be helpful to create a changelog file or use GitHub Releases to document the changes in each version.

**Comment by pyros2097** [comment]
Yeah I think we could do one of those. I thought no one was using this library so didn't bother.
I think something like this format will be good.
https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md
Also there is one known issue that the code generated for large files by the proc macro gets too huge that the rust parser starts choking at the lexer and takes too long to compile.
I tried to get a solution using the rust built in `include_bytes!()` which seemed to solve the perf issue but then changed the api significantly. So the changelog will be really useful here.

**Comment by Mcat12** [comment]
This is a useful site: https://keepachangelog.com/

**Comment by Mcat12** [comment]
When do you plan on making a new release? I see the CI is currently failing, but I think it is an issue with nightly and another dependency.

**Comment by pyros2097** [comment]
Its an issue with the nightly version. Should have hardcoded the nightly version in the travis script.
Also should add the nightly version that this package works with in the readme. Also try to move away from nightly to stable if its possible.
Didn't get much time to work on it. Will try to add the changelog this weekend and workout the travis issues for now.
Also is it breaking for you? Then we need to find/explore ways to move it to stable rust even if the api changes a bit.

**Comment by Mcat12** [comment]
I'm on an older nightly, and the master branch works for me (nightly-2018-03-07).

**Comment by pyros2097** [comment]
Hmmm... It seems travis doesn't support specifying a nightly version. Also other nightly based projects like rocket also seem to be braking.

**Comment by Mcat12** [comment]
You can test manually and release with a supported version of nightly specified.

**Comment by pyros2097** [comment]
Changelog Done. Thanks for the push.
