### ISSUE TITLE
Feature Request: Include some file metadata w/ the file

### ISSUE THREAD

**Issue by NfNitLoop** [pyros2097/rust-embed#140]
I'm using rust-embed to create an executable that serves some files over HTTP.

HTTP has support for metadata, like the [Last-Modified] date, and [ETag], which can help browser caches.

[Last-Modified]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified
[ETag]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

If rust-embed included the last-modified date, as well as some cryptographic hash (say, sha256 and/or sha512?), then I could use that data to serve Last-Modified and ETag headers to help browsers more effectively cache these resources.

In the meantime, I suppose I could work around the issue by calculating content hashes in memory. It'd be handy to have them at compile time, though.

**Comment by AzureMarker** [comment]
@pyros2097 what do you think of this? We could probably have a separate function on `RustEmbed` which exposes the metadata, like:
```rust
fn metadata(path: &str) -> Option<FileMetadata>;
```

`FileMetadata` would then be an opaque struct so we could add more fields to it without breaking backwards compatibility.

**Comment by NfNitLoop** [comment]
Sounds great!

> It should probably go behind a feature flag (then we wouldn't even need a new major release, just minor).

I think additive changes are fine in minor releases even without a feature flag. (<https://semver.org/>) But, a feature flag might be nice so folks don't incur any additional processing time that they don't opt into.

**Comment by AzureMarker** [comment]
Oh right, yeah either way we wouldn't need a major release.

**Comment by pyros2097** [comment]
@AzureMarker this looks great. Let's do a major release. I think it makes sense to expose this to everyone since most users use it for websites (including me) and the extra meta would really help.

**Comment by NfNitLoop** [comment]
It might be nice if that `FileMetadata` type also returns the same `Cow<'static, [u8]>` that you get from `get(file_path)`, that way you don't have to make a call to both `get(path)` and `metadata(path)`.

```rust
if let Some(metadata) = my_embed.metadata(path) {
   do_something(&metadata.bytes, &metadata.sha512);
}

// vs:
match (my_embed.get(path), my_embed.metadata(path)) {
   (Some(bytes), Some(metadata)) => {
      do_something(&bytes, &metadata.sha512);
   }, 
   (None, None) => { /* do nothing */ },
   _ => { panic!("This should never happen?"); }
}
```

**Comment by pyros2097** [comment]
Since we are releasing a new major version, does it make sense to change the api of `get` to return a File object,
```rust
fn get(path: &str) -> Option<File>;
```

That way we have all the fields like name, size, meta under it so that it could be useful for other cases.

It would be nice if we could update our examples to have implement http caching in this likes of this,
```golang
package main

import (
  "net/http"

  "github.com/pyros2097/go-embed/examples/assets"
)

func main() {
  http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
    println("GET " + req.URL.Path)
    data, hash, contentType, err := assets.Asset("public/", req.URL.Path)
    if err != nil {
      data, hash, contentType, err = assets.Asset("public", "/index.html")
      if err != nil {
        data = []byte(err.Error())
      }
    }
    res.Header().Set("Content-Encoding", "gzip")
    res.Header().Set("Content-Type", contentType)
    res.Header().Add("Cache-Control", "public, max-age=31536000")
    res.Header().Add("ETag", hash)
    if req.Header.Get("If-None-Match") == hash {
      res.WriteHeader(http.StatusNotModified)
    } else {
      res.WriteHeader(http.StatusOK)
      _, err := res.Write(data)
      if err != nil {
        panic(err)
      }
    }
  })
  println("Server running on 127.0.0.1:3000")
  http.ListenAndServe(":3000", nil)
}
```
https://pkg.go.dev/github.com/pyros2097/go-embed

**Comment by AzureMarker** [comment]
The `File` struct would have to be our own and not the std's, because that one is backed by a real file on a file system. It would also make sense to rename it to something like `EmbeddedFile`.

**Comment by AzureMarker** [comment]
I've started working on this and should have a PR up soon.

**Comment by pyros2097** [comment]
> The File struct would have to be our own and not the std's, because that one is backed by a real file on a file system. It would also make sense to rename it to something like EmbeddedFile.

Yep exactly. Thought I should have made it more clear. `EmbeddedFile` makes more sense. 

Thanks.

**Comment by NfNitLoop** [comment]
👋 I'd love to use these changes.  If there's a chance of a release soon, I'll wait for that. If not, should I just depend on whatever is in the main branch?

**Comment by pyros2097** [comment]
@NfNitLoop sorry got sidetracked from doing the release as I was too lazy to update the changelog and readme. I've done it now.

**Comment by NfNitLoop** [comment]
No problem at all. Thanks! 😊

**Comment by NfNitLoop** [comment]
It's working great. 🎉  

Though, I noticed that the [crates.io page][1] doesn't mention the new EmbeddedFile, even though [the readme][2] does. 

[1]: https://crates.io/crates/rust-embed
[2]: https://github.com/pyros2097/rust-embed/blob/master/readme.md

**Comment by pyros2097** [comment]
Ohh I published it first before updating the readme. I don't there is a way to circumvent this without releasing v6.0.1. Well I guess its ok for now.
