### ISSUE TITLE
Compiles very slowly when including large files

### ISSUE THREAD

**Issue by lukad** [pyros2097/rust-embed#15]
When I use the macro in release mode to include a large file (I first tried with ~500 kB) it takes a very long time to compile. The culprit here is the huge `vec![..]` literal which seems to be very expensive.

Using `include_bytes!` would solve the problem because it's a compiler built-in that doesn't create a Vector and push one Byte at a time into it.

See my PR #16.

To reproduce run
```
dd if=/dev/urandom of=examples/public/index.html bs=1k count=500; time cargo run --release --example basic
```

**Comment by pyros2097** [comment]
Yes I know. Did try to solve the problem with include_bytes but failed it seems you have succeeded. Will merge.

**Comment by pyros2097** [comment]
Also @lukad Thanks.

**Comment by lukad** [comment]
You're welcome! And thanks for merging this so quickly.
