### ISSUE TITLE
Rocket example with Rocket 0.5.0-rc.1 & Rust 1.56.1

### ISSUE THREAD

**Issue by DuredhelFinceleb** [pyros2097/rust-embed#157]
Hi,

The Rocket example does not compile with Rocket 0.5.0-rc.1 & Rust 1.56.1

sized_body complains the 'size' parameter is missing
The syntax "fn index<'r>() -> response::Result<'r>" is a no go, compiler complains about it non implementing some black magic thing with 2 lifetimes and if you add the missing lifetime then it complains there are too many lifetimes.
I'm new to Rust so it was way above my level.

Maybe add a comment static which version of Rust/Rocket this will compile against?

As for Rocket 0.5.0-rc.1 & Rust 1.56.1, here is what I've done to make it work:
- provide d.data.len() to the size parameter of sized_body
- create a struct to hold everything used by the routes of the example; EmbeddedFile, PathBuf & ContentType
- implemented a Responder on that struct follwing instructions on https://api.rocket.rs/v0.5-rc/rocket/response/trait.Responder.html#example  : it contains essentially the code which is in the routes of the example. 
- use that implementation in the routes

I'm attaching the code to this issue. As I said, I'm new to Rust so I'm really not sure I did it The Right Way, hence the reason why I'm not submitting a PR right away
[rocket_0.5.0-rc.1.txt](https://github.com/pyros2097/rust-embed/files/7599133/rocket_0.5.0-rc.1.txt)

**Comment by AzureMarker** [comment]
Don't worry about submitting a PR too early. It's easier to collaborate and see the changes in a PR than in a text file. If you really want, you can even open the PR in draft.

Our Cargo.toml file shows the version of Rocket we compiled against:
https://github.com/pyros2097/rust-embed/blob/34299eb1bc41da92fe5d474036d49b8f2c5b3c00/Cargo.toml#L60

Feel free to open a PR and we can add comments.

**Comment by AzureMarker** [comment]
I will note though that this would be a simpler implementation:
```rust
#[macro_use]
extern crate rocket;

use rocket::http::ContentType;
use rocket::response::content::Html;
use rust_embed::RustEmbed;

use std::borrow::Cow;
use std::ffi::OsStr;
use std::path::PathBuf;

#[derive(RustEmbed)]
#[folder = "examples/public/"]
struct Asset;

#[get("/")]
fn index() -> Option<Html<Cow<'static, [u8]>>> {
  Asset::get("index.html").map(|d| Html(d.data))
}

#[get("/dist/<file..>")]
fn dist(file: PathBuf) -> Option<(ContentType, Cow<'static, [u8]>)> {
  let filename = file.display().to_string();
  Asset::get(&filename).map(|d| {
    let content_type = file
      .extension()
      .and_then(OsStr::to_str)
      .and_then(ContentType::from_extension)
      .unwrap_or(ContentType::Bytes);
    (content_type, d.data)
  })
}

#[rocket::launch]
fn rocket() -> _ {
  rocket::build().mount("/", routes![index, dist])
}
```

**Comment by DuredhelFinceleb** [comment]
No problem, I've adapted to my own project and it works great!
Not sure on how you want me to contribute this though: I mean if you want to keep both examples (in 0.4 & 0.5) than I'm not sure how to impact Cargo.toml
In the PR I would submit this with changes to Cargo.toml to use rocket 0.5 (with the added benefit that it does not need nightly anymore): would that be OK for you?

**Comment by AzureMarker** [comment]
Yeah, if you're still interested in opening a PR, it would involve bumping the rocket version and replacing the example with the one from this issue. However now that I think of it, there are also some more CI changes needed related to nightly, so I'd be happy to make the changes myself too. Up to you though!

**Comment by DuredhelFinceleb** [comment]
I'm not sure what those CI changes would be, so maybe its best that you do the changes yourself I'd say.
Thanks again for your help!
