### ISSUE TITLE
Directory traversal attack allowed when running in debug mode

### ISSUE THREAD

**Issue by 5225225** [pyros2097/rust-embed#159]
```rust
#[derive(rust_embed::RustEmbed)]
#[folder = "src/"]
struct Asset;

fn main() {
    let d = Asset::get("../../../etc/passwd").unwrap().data;
    println!("{}", String::from_utf8_lossy(&d));
}
```

This code will (assuming you have the correct number of `../`s), print out the contents of your `/etc/passwd`.

**Comment by AzureMarker** [comment]
Thanks for the report. I'll open a PR ASAP.

**Comment by pyros2097** [comment]
Fix is released in v6.3.0. Thanks for finding the vulnerability @5225225.

**Comment by 5225225** [comment]
I'll file a https://rustsec.org/ vuln today to hopefully get anyone on vulnerable versions to upgrade, assuming they run cargo-audit or similar.

**Comment by 5225225** [comment]
Also, the readme / changelog needs to be updated.

**Comment by pyros2097** [comment]
Ahh I forgot to push my commit. Thanks.
