### ISSUE TITLE
Axum example is depricated.

### ISSUE THREAD

**Issue by makorne** [pyros2097/rust-embed#161]
Hi!
```
type Body = Full<Bytes>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `IntoResponse`
```

Looks like the example based on axum version 0.2.8 but IntoResponse changed since [0.3](https://github.com/tokio-rs/axum/pull/448) 

So in current axum 0.4 it does not compile.

**Comment by pyros2097** [comment]
@makorne would you be interested in making a PR for this?

**Comment by makorne** [comment]
Sorry I am just trying axum and I have not enough skills.
