### ISSUE TITLE
cant embed react production build

### ISSUE THREAD

**Issue by tungs0ul** [pyros2097/rust-embed#168]
I'm using the warp example with my react build but it only loads the index.html and fails to load all the .js files.
Can some one help please? Code is pretty much the same with warp example

`GET http://localhost:3000/assets/index.2e209183.js net::ERR_ABORTED 404 (Not Found)
      
GET http://localhost:3000/assets/index.e9ef52d3.css net::ERR_ABORTED 404 (Not Found) 
        
GET http://localhost:3000/assets/vendor.b30eca7b.js net::ERR_ABORTED 404 (Not Found)`

**Comment by AzureMarker** [comment]
I don't see any problems after running the warp example, so I can't reproduce this. Double check you're using the right path when getting the files.

**Comment by tungs0ul** [comment]
Yes the warp example works for me too. But what I mean is instead of folder examples/public I use my react build. 
`
#[derive(RustEmbed)]
#[folder = "examples/public/"]
`

In my case 
`
#[derive(RustEmbed)]
#[folder = "client/build/"]
`
and it loads only the index.html

**Comment by AzureMarker** [comment]
rust-embed doesn't do anything special for HTML vs JS files. Can you share the full example?

**Comment by AzureMarker** [comment]
Debugged over email - was a warp config issue.
