### ISSUE TITLE
Changelog Misses Some Changes And Versions

### ISSUE THREAD

**Issue by Mcat12** [pyros2097/rust-embed#17]
Not included in the changelog are these PRs:
- #2 - Use file of the same name.
- #4 - Fix bug in filenames with dashes.
- #5 - Add asset listing function.
- #7 - Ignore some clippy lints in generated code.
- #9 - Use `$crate` to improve macro hygiene.
- #11 - Removes Cargo.lock so the library can be used on the latest nightlies
- #12 - Removes the `log` macros in debug mode. This caused errors if you didn't include the log macro in your crate, or if you used Rocket (they have some macros with the same names).
- #13 - Moves the `use` statements in the debug code to not conflict with the other `use` statements of the file the macro is used in.

These are all useful to see in a changelog so that people can see what bugs each release fixed. Besides PRs, there are probably some missed changes you directly made without going through a PR.

Also missing are these versions:
- 0.3.0
- 0.3.2
- 0.3.4
- 0.3.5
- 0.4.0
- 0.5.1
- 0.5.2
- 1.0.0
- 1.1.0

**Comment by pyros2097** [comment]
Sure. Will take it up next weekend.

**Comment by pyros2097** [comment]
Done.
