### ISSUE TITLE
Consistent ordering of embedded files

### ISSUE THREAD

**Issue by apognu** [pyros2097/rust-embed#171]
Right now, as far as I can tell, and as reported in [an issue](https://github.com/apognu/tuigreet/issues/60) in one of my projects, the ordering of the files in the built binary is undefined, since `rust-embed` [uses WalkDir](https://github.com/pyros2097/rust-embed/blob/master/utils/src/lib.rs#L56) under the hood, which outputs files [in undefined order](https://docs.rs/walkdir/latest/walkdir/struct.WalkDir.html) unless the `sort_by` function is used.

Functionally, this doesn't matter, but it does pose issues for projects (and OSes and build processes) aiming or desiring reproducible builds.

As far as I can tell, this should be a pretty painless change, and backward compatible since the original order was always undefined.

I can try and craft a PR if it could help (and if this is wanted).

**Comment by AzureMarker** [comment]
Yeah that makes sense to me. Reproducible builds are good.

**Comment by apognu** [comment]
Do you want me to provide a PR?

**Comment by AzureMarker** [comment]
Yeah, that would be great

**Comment by apognu** [comment]
Done.

**Comment by pyros2097** [comment]
Released in v6.4.0
