### ISSUE TITLE
Make it work on Stable Rust

### ISSUE THREAD

**Issue by pyros2097** [pyros2097/rust-embed#18]
It seems many useful libraries like serde, diesel are working in stable rust right now. We should also move this to use stable rust so that it could be more in tune to work in production environments.

Here is the list of changes I can think of,
- [ ]  Remove `#![feature(attr_literals)]`

**Comment by Mcat12** [comment]
I found that failure_derive does a similar derive thing, but without nightly:
```rust
#[derive(Fail, Debug)]
#[fail(display = "An error occurred.")]
```
https://boats.gitlab.io/failure/derive-fail.html
