### ISSUE TITLE
Docs for get() function

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#25]
It would be useful to know which methods can be called on the `Asset` struct and which signatures they have. E.g. can `get` only be called with a &str or also with a `Path`?

EDIT: I looked at the source and it looks like `get` can only be called with a &str, why not with a `P: AsRef<Path>` (called with relative paths)?

**Comment by pyros2097** [comment]
Well I didn't think there was need as a path could be always converted to a string and this was standard from all other forms of embedding tools in other languages. Maybe we could add another method to handle this use case and also will need to improve the docs.

**Comment by pyros2097** [comment]
Also where do you want the docs since documenting macros is pretty hard inline. Maybe just adding it in the readme for now will do fine.

**Comment by Boscop** [comment]
Yes, it's enough to write it in the Readme (the signature of `get()`).

**Comment by pyros2097** [comment]
Done.
