### ISSUE TITLE
Avoid allocating new Vec for every get() call

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#26]
This allocates a new Vec for every get() call:
https://github.com/pyros2097/rust-embed/blob/b509d63985c4079c0cd2aaf2e3c951ee249003d5/src/lib.rs#L62

It would be better to return a `&'static [u8]` by writing this instead:
```rust
    #key => Some(&include_bytes!(#canonical_path_str)[..]),
```

And then `pub fn get(file_path: &str) -> Option<&'static [u8]> {`

**Comment by pyros2097** [comment]
Also at the time most web frameworks supported the Vec<u8> as a response type.
Will need to verify this if it is possible both in dev mode and release mode. If it is more performant and handles integration with existing frameworks well then it should be a no problem. (albeit this can be solved easily)
Also would like to know if it allocates the whole file data in memory or only references that part of the memory and returns a pointer to it?

**Comment by pyros2097** [comment]
But will be :sob:  as I have to remove the cool screenshots of my terminal from the readme.md

**Comment by Boscop** [comment]
`to_vec()` always allocates a Vec and copies the data over.
If that's necessary in the user's use case, then the client code should call `to_vec()` (`Asset::get(path).to_vec()`). It should be up to the user to decide if the allocation is necessary.

**Comment by pyros2097** [comment]
Asserted. Then this will be a refactor and change in the api. Will need to push a new major for this and correct the examples. Will do this and add the path method/docs for this in the next major release 4.

**Comment by pyros2097** [comment]
Nice.. How do we solve this? `&'static [u8]` for both debug and release? In debug its dynamically loaded right how do we make it &' static.

**Comment by Boscop** [comment]
If we change the function to return `impl Into<Vec<u8>> + AsRef<[u8]>` instead then one can `.into()` the result to get a `Vec<u8>`, and it won't clone if it's already a `Vec<u8>`. And then `.as_ref()` still works.

**Comment by pyros2097** [comment]
@vemoo any thoughts on this.
Shall we go ahead on change the return type as you had done in this PR.
https://github.com/pyros2097/rust-embed/pull/40

`impl Into<Vec<u8>> + AsRef<[u8]>` seems like a better approach for integration with other webframeworks.

@Boscop Also why do you need to return a `Vector<u8>` in actix. I thought it takes a [u8] also according to the example.
https://github.com/pyros2097/rust-embed/blob/master/examples/actix.rs#L18

**Comment by Boscop** [comment]
Ah, I hadn't seen the `Body::from_slice` method. That works, but other web server frameworks (or other use cases) will still require an owned `Vec` so I think we should still change the return type to enable this optimization. And I won't break any existing code.

**Comment by vemoo** [comment]
> If we change the function to return `impl Into<Vec<u8>> + AsRef<[u8]>` instead then one can `.into()` the result to get a `Vec<u8>`, and it won't clone if it's already a `Vec<u8>`. And then `.as_ref()` still works.

When in debug a `Vec<u8>` is returned but when in release a `&'static u8`. So this will only be an optimization when in debug. In release calling `.into()` will allocate a new `Vec<u8>`.

**Comment by Boscop** [comment]
@vemoo No, because `.into()` (from `Into<Vec<T>>` is a no-op when called on a `Vec<T>`.

**Comment by vemoo** [comment]
@Boscop but this macro doesn't create a `Vec<u8>` on release, it returns the `&'static [u8]` directly from `include_bytes!(...)`: https://github.com/pyros2097/rust-embed/blob/3421ff019a09f4955c5e05aef75986ad318d7440/impl/src/lib.rs#L59
So `.into()` will use https://doc.rust-lang.org/src/alloc/vec.rs.html#2236-2245

**Comment by Boscop** [comment]
Ah right, but it will still prevent a `Vec` clone in debug mode, so it's still worth doing (no drawbacks).

**Comment by vemoo** [comment]
I don't think that's dynamic dispatch. All the posible types are know at compile time. We just go from
```rust
match Assets::get(&path) {
    Some(Vec<u8>) => ...,
    None => ...,
}
```
in debug or 
```rust
match Assets::get(&path) {
    Some(&'static u8) => ...,
    None => ...,
}
```
in release to
```rust
match Assets::get(&path) {
    Some(Cow::Borrowed(&'static )) => ...,
    Some(Cow::Owned(Vec<u8>)) => ...,
    None => ...,
}
```
both in debug and release, with the added benefit that we have access to the static lifetime, which allows using https://docs.rs/actix-web/0.7.14/actix_web/enum.Binary.html#impl-From%3C%26%27static%20%5Bu8%5D%3E which wasn't possible before.

**Comment by Boscop** [comment]
@vemoo Yea, by dynamic dispatch I meant the matching on the Cow..
But we're matching already, so it's "ok" from that point, if the information that the lifetime is `'static` prevents actix from having to copy the slice..

But with the Cow solution, we'd then require client code to have essentially the same code in both cases of the Cow match (it will just choose a different instance of `Binary::from` at compile-time) :/
But that seems to be unavoidable..
