### ISSUE TITLE
Printing to stdout during compilation should be avoided

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#27]
rust-embed prints to stdout during compilation:
https://github.com/pyros2097/rust-embed/blob/2025bfb7b8becb4f281efa5cd3febc611ba98fcb/src/lib.rs#L56
macros should not do that.
It breaks editors that parse the json output:
https://github.com/rust-lang/rust-enhanced/issues/310#issuecomment-405052274

All occurrences of `println` and `eprintln` in that file should be removed.

**Comment by pyros2097** [comment]
Well.. I thought it would be good to see which files are being loaded into the binary at compile time. That would make it easy to find out the progress of the compilation and also if some large file is taking too long. Does printing to stderr is a better approach or removing it altogether better. Anyways I'm ok with removing the println no one else has issues with it.

**Comment by pyros2097** [comment]
But will be :sob:  as I have to remove the cool screenshots of my terminal from the readme.md

**Comment by Boscop** [comment]
The `include_bytes!()` call should be very fast though, right?
It's not really "compiling" (processing) the included files..
So I think it's ok to have no output about this. People who are using rust-embed will know that if it takes a bit longer, it's because of the embedded files :)
I think a better solution is to just mention it in the Readme: "Be aware that compilation might take a little bit longer when embedding a large number of files."

**Comment by pyros2097** [comment]
Ok. You convinced me. And it seems no one is going to miss it. Do you want to raise a PR for it or should i do it.

**Comment by Boscop** [comment]
I'm currently traveling on vacation with only my phone, so I think it'd be faster if you do it :)
