### ISSUE TITLE
Method for getting a list of the available files

### ISSUE THREAD

**Issue by norcalli** [pyros2097/rust-embed#29]
It would be nice to have a method such as `fn list(&self) -> Vec<Path>` or `fn list(&self) -> Vec<String>` to get a list of the available files. My use case is that I want to have a few specifications for different models of TVs, and rather than typing out the names of the models twice, I would just name the file describing the TV after the appropriate display option, and then retrieve that list in the program.

**Comment by Boscop** [comment]
Yes, please! I'm getting 404 for all my files..

**Comment by pyros2097** [comment]
404 for all your files... maybe some. Not all. Did you follow the pattern in the example.
Anyways guys this might take some time as my local developing system got messed up pretty bad and now rustc is not working in my current os (Solus). I have to reinstall it or install Ubuntu to make any new fixes/features. Will try by the end of this week.

**Comment by Boscop** [comment]
@pyros2097 Yes, it works fine now (with `target/deploy`), but being able to get an iterator over the embedded files (either their paths or `(path, file)` (like `(key, value)` with `HashMap`)) would still be useful..
