### ISSUE TITLE
include macros

### ISSUE THREAD

**Issue by flosse** [pyros2097/rust-embed#3]
why don't you use the standard macros?

http://doc.rust-lang.org/std/macro.include_bytes!.html
http://doc.rust-lang.org/std/macro.include_str!.html

**Comment by pyros2097** [comment]
@flosse Thanks for the info didn't see it till now. The thing about standard macros is you need to know the file path. Whereas in my usecase it dynamically generates the list of files and also allows you to serve the files as a folder for a static web server. This is very common and used a lot in go web development.

**Comment by flosse** [comment]
> Whereas in my usecase it dynamically generates the list of files and also allows you to serve the files as a folder for a static web server

You could mention this in the README to point the difference and avoid confusion :)

**Comment by pyros2097** [comment]
Fixed
