### ISSUE TITLE
trailing slash after dir should not be mandatory

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#30]
https://github.com/pyros2097/rust-embed/blob/93bf8334488a8387ab419164aeabf7855ceda29d/src/lib.rs#L23
The trailing slash after dir should not be mandatory, for usability/convenience reasons!
This line should be changed to `let name = &format!("{}/{}", folder_path, file_path);` 
(If the dir path already has a trailing slash, double slash won't be a problem. Or you could pass the slice up to the trailing slash.)

**Comment by pyros2097** [comment]
Sure!. As soon as I get my rustc setup working again. Is there any other way I could get rustc working other than docker. Like using rust play or something.

**Comment by Boscop** [comment]
You mean locally or for CI?
Locally I just have it installed normally (on Windows with rustup installer, on arch I installed rustup through pacman and then everything else with rustup).
For CI you could use travis CI so that it also runs the tests automatically on every commit.

**Comment by Boscop** [comment]
@pyros2097 Why not just use `Path::join`? :)
