### ISSUE TITLE
In debug build, it should work, no matter which folder `cargo` is invoked from!

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#34]
Try to run `cargo run --example basic` from the `examples` subfolder, it will crash.
The procmacro should make sure that it works, no matter where cargo is called from! 
(Also important for workspaces, where the exe could be in the toplevel or in a sub folder.)

**Comment by yatesco** [comment]
Note: #99 - it doesn't seem to matter whether running a `debug` or `release` build - the path in the `folder` directive is always relative to the current directory.

**Comment by pyros2097** [comment]
Yes. I guess it needs to get the current workspace from cargo or some other way and not use the current working directory as the base path.

**Comment by cmcqueen** [comment]
For my use-case, I actually preferred the old behaviour of looking for the files relative to the current directory. My use-case is, I want to do a debug cross-compile for an embedded Linux target, then copy the debug executable plus the files to the target at a different directory than what it was compiled in.

But, I guess I will just use feature `debug-embed` instead.
