### ISSUE TITLE
examples don't work on windows for non top level files because of path separator

### ISSUE THREAD

**Issue by vemoo** [pyros2097/rust-embed#36]
When building on windows the keys generated for the paths by the macro use \ as a path separator.

If the main use case for this crate is to embed web assets, then it could be usefull to replace \ with / when building on windows, or maybe easier when `std::path::MAIN_SEPARATOR == '\\'`.

**Comment by pyros2097** [comment]
PR's are welcome. Also any clues on how to solve this just string replace. Also it would be good to have an appveyor test for windows.

**Comment by vemoo** [comment]
Ok, I can create a PR. I think string replace only when on windows should be ok, since "/" is not valid for filename or directory names.

I can try to setup an appveyor.
