### ISSUE TITLE
Binary mode should be controlled by a feature not by debug mode

### ISSUE THREAD

**Issue by Xudong-Huang** [pyros2097/rust-embed#41]
User should be able to specify a feature flag to control whether the resources should be embedded in binary or read from fs.

It would be nice with the default feature enable the binary mode in both debug and release version. After all this crate's purpose is embed resource into binary.

**Comment by pyros2097** [comment]
So your'e saying always embed the files in the binary by default even in development. I'm ok with that but wont it increase the compilation time if the file is big or if there are many files?
Also how would a another user retain the old behavior of load from fs in dev and binary in release?

@lukad @jgrowl  @Mcat12 @vemoo @Gowee any insights here?

**Comment by lukad** [comment]
I don't think the default behavior should be to embed by default. That would break the workflow for most users who are embedding assets in web servers in something similar. They would have to rebuild after changing these assets.

But I like having the behavior configurable via a feature. Would it be possible to define default features per mode like this?

```
[features]
default = []
release = ["binary"]
```

**Comment by lukad** [comment]
Or maybe we can create a feature "debug-embed" and change the configuration checks to `#[cfg(any(debug_assertions, not(feature = "debug-embed")))]` for not embedding and `#[cfg(not(debug_assertions))]` for embedding.

Then, if you can just add the "debug-embed" feature to your Cargo.toml if you want.

**Comment by Mcat12** [comment]
I agree with @lukad's proposal.

**Comment by lukad** [comment]
Should I pick this up and create a pull request for my proposal?

**Comment by pyros2097** [comment]
@lukad Be my guest. I was waiting for someone to do it.
