### ISSUE TITLE
Define an actual RustEmbed trait

### ISSUE THREAD

**Issue by Tangent128** [pyros2097/rust-embed#48]
The current macro only generates an `impl {}` block; that is useful as it avoids a need to `use` any traits to access the `get` and `iter` methods, but the lack of a trait prevents any generic extensions.

Defining & exporting a RustEmbed trait, and implementing it as part of the derive, could allow things like extension crates to handle the boilerplate of binding assets to different frameworks, path globbing extension methods, etc.

**Comment by pyros2097** [comment]
Hmmm seems interesting. Exposing a trait so that others can implement it. If you've got an idea on how to implement it. Give it a shot and we can review it.
