### ISSUE TITLE
How to make it work in workspace with cargo test?

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#58]
I want to embed the folder `workspace/crate_foo/bar`, so I do:
```rust
#[derive(RustEmbed)]
#[folder = "crate_foo/bar"] // relative to workspace root
pub struct Assets;
```
But when I do `cargo test`, it fails when the doc-tests are run:
```
# cargo test -p crate_foo
   Compiling crate_foo v0.1.0 (/usr/src/workspace/crate_foo)
    Finished dev [unoptimized + debuginfo] target(s) in 4.14s
     Running target/debug/deps/crate_foo-ba8abb39df8832bd

running 2 tests
test [..] ... ok
test [..] ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests crate_foo
error: proc-macro derive panicked
  --> /usr/src/workspace/crate_foo/src/templates.rs:50:14
   |
50 |     #[derive(RustEmbed)]
   |              ^^^^^^^^^
   |
   = help: message: #[derive(RustEmbed)] folder 'crate_foo/bar' does not exist. cwd: '/usr/src/workspace/crate_foo'

error: test failed, to rerun pass '--doc'
```

Because apparently, for normal tests, it uses cwd `workspace` but for doc-tests, it uses cwd `workspace/crate_foo`, so it will try to embed `workspace/crate_foo/crate_foo/bar` when running doc-tests, but why?

I tried to use `#[cfg(not(test))]` on a wrapper module to only conditionally embed the dir, but it doesn't work..
How can I make it work?
Is there a `#[cfg(not(doc_tests))]` or something? How can I embed only when doc-tests aren't run?

**Comment by s3bk** [comment]
I can see three approaches:
 1. make relatives paths relative to the crate root (using $CARGO_MANIFEST_DIR)
 2. allow environment variables as part of the path (using (shellexpand)[http://netvl.github.io/shellexpand/shellexpand/index.html])
 3. make the path relative to the file using the macro (using the Span::source_file().path())

**Comment by Boscop** [comment]
@s3bk: Thanks. I prefer solution 3, because std's macros to include files also use paths relative to the current file. And this is the most robust & intuitive solution.

**Comment by Boscop** [comment]
@s3bk But it looks like we can't use option 3, because [`syn::DeriveInput`](https://docs.rs/syn/0.15.29/syn/struct.DeriveInput.html) doesn't expose spans :(
