### ISSUE TITLE
Fill in changelog from 5.0.1 to 5.1.0

### ISSUE THREAD

**Issue by Mcat12** [pyros2097/rust-embed#76]
There were a lot of versions published between 5.0.1 (last documented in changelog) to 5.1.0. The changelog should be updated with the changes these versions made.

**Comment by pyros2097** [comment]
@Mcat12 versions 5.0.5, 5.0.4 5.0.3, 5.0.2 where published as I was trying to fix that import error and couldn't get it working properly and my lack of time to find a better way to test it. I have yanked those versions now here https://crates.io/crates/rust-embed/versions.
Does that need to be documented also?

**Comment by Mcat12** [comment]
If any of the changes made in those versions exist in the current version and aren't documented, then they should be documented. Otherwise, you probably don't need to document the yanked versions since they were just used for testing.

**Comment by pyros2097** [comment]
Sure. None of those changes made it in the current version. So it's ok. I'm closing this issue then.
