### ISSUE TITLE
doesn't work with files generated by `nuxt.js`

### ISSUE THREAD

**Issue by GopherJ** [pyros2097/rust-embed#79]
Hello, I tried to use `nuxt.js` and generated some static pages using `nuxt generate`, while I load these files using a static file server it works perfectly but while I load it using `rust-embed` it doesn't work anymore.

Do you have some ideas why it happens? I'll try to make a repro.

**Comment by Mcat12** [comment]
A reproducible example would be very useful. Are you sending the right content types?

**Comment by Mcat12** [comment]
@GopherJ Were you able to reproduce this?
