### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by madmaxio** [pyros2097/rust-embed#8]
Is it rust macro perhaps?

**Comment by pyros2097** [comment]
Yes it is a rust macro.

**Comment by madmaxio** [comment]
Thx,

**Comment by memoryruins** [comment]
The repo description was also set to "Marco"

![gh-description](https://i.imgur.com/eRCxtXY.png)

**Comment by pyros2097** [comment]
Haha.. Maybe it wasn't on that day. We need a historical view into the repo description. You see previously this was a code generator.
