### ISSUE TITLE
When rust-embed is used in a lib, the folder_path is relative to the lib, not the binary using it.

### ISSUE THREAD

**Issue by scullionw** [pyros2097/rust-embed#80]
1. I made a library crate "pypack" that uses rust-embed.
2. I made a binary crate that uses that library crate.
3. I would expect the folder used for the Asset folder path to be relative to the binary cargo.toml, is that not the case?

example:

```
error: proc-macro derive panicked
  --> C:\Users\LUNA\.cargo\git\checkouts\pypack-071d8f8d2bc34e74\06f6da1\src\lib.rs:13:10
   |
13 | #[derive(RustEmbed)]
   |          ^^^^^^^^^
   |
   = help: message: #[derive(RustEmbed)] folder 'dist/' does not exist. cwd: 'C:\Users\LUNA\.cargo\git\checkouts\pypack-071d8f8d2bc34e74\06f6da1'
```

**Comment by Boscop** [comment]
You can do `#[folder = "$CARGO_MANIFEST_DIR/foo/bar"]`

**Comment by scullionw** [comment]
that doesn't seem to work:

```
error: proc-macro derive panicked
  --> C:\Users\LUNA\Desktop\Projects\pypack\src\lib.rs:15:10
   |
15 | #[derive(RustEmbed)]
   |          ^^^^^^^^^
   |
   = help: message: #[derive(RustEmbed)] folder '$CARGO_MANIFEST_DIR/dist' does not exist. cwd: 'C:\Users\LUNA\Desktop\Projects\pypack'
```

I don't think the env var is being expanded. I'm not sure, but I think something like 

`concat!(env!("CARGO_MANIFEST_DIR"), "/", "dist/");`

would be needed, but the proc macro can only accept literals..

**Comment by pyros2097** [comment]
I haven't tested this on windows. But maybe the path separator "/" is the issue. I don't know if we are handling it correctly in rust-embed.

**Comment by Boscop** [comment]
@scullionw You need to enable the `interpolate-folder-path` feature :)

**Comment by pyros2097** [comment]
Ahh got it thats why

**Comment by Boscop** [comment]
Yeah, the feature has a kind of non-obvious name..
Maybe we can rename it to "shell-expand" (to have it named differently than the crate, but still using the fitting name)?
Or we can enable it by default and users who don't want it can opt out?

**Comment by Mcat12** [comment]
I'll look into adding a custom warning to detect this case. We should recommend turning on that feature if the user is trying to use a variable.
