### ISSUE TITLE
Is there a way to just instantiate an Asset struct?

### ISSUE THREAD

**Issue by ReactorScram** [pyros2097/rust-embed#87]
This would let me work around #34 like so:

1. Enter the main () function
2. Figure out what directory I want to load assets from (e.g. the project root)
3. Pass that directory, and the assets directory to some new () func (e.g. Asset::new ("/myproject", "public/html")
4. The new () func returns an Asset which I can pass to other functions by shared reference. I could even create multiple instances if I want to swap between two folders while the program is running.

The existing global functions could be implemented on top, by creating a global object that has the two directories fixed at compile time.

If I can find a way to do that, would you take a PR?

**Comment by pyros2097** [comment]
Sure. But I think that would need a major version change. And break existing users.

**Comment by Mcat12** [comment]
If you have just two different possibilities, you could embed both and choose at runtime which to use. You should be able to reference it as a `&dyn RustEmbed` (aka `&'static dyn RustEmbed`). If you don't want to have both embedded at the same time, then make the choice in your build.rs file and pass the computed path to rust-embed.

**Comment by Mcat12** [comment]
There is an alternative method to achieve the desired behavior and the root issue has been fixed (#34), so this issue will be closed.
