### ISSUE TITLE
`OUT_DIR` says it "does not exist"

### ISSUE THREAD

**Issue by tversteeg** [pyros2097/rust-embed#88]
I have the following code:

```rust
#[derive(RustEmbed)]
#[folder = "$OUT_DIR/gui/"]
struct GuiAsset;
```

And when I try to compile this I get the following error: 

```
error: proc-macro derive panicked
  --> src\gui.rs:47:10
   |
47 | #[derive(RustEmbed)]
   |          ^^^^^^^^^
   |
   = help: message: #[derive(RustEmbed)] folder '$OUT_DIR/gui/' does not exist. cwd: 'E:\Repo\castle-game'
```

It looks like `$OUT_DIR` isn't resolved properly, even though PR #67 should have fixed this.

**Comment by Mcat12** [comment]
Did you set the `interpolate-folder-path` feature on `rust-embed`? That is required to support environment variables in the path.

**Comment by tversteeg** [comment]
Yes this seems to work, thanks. Maybe this feature should be documented somewhere? I couldn't find it at all.
