### ISSUE TITLE
Compress assets?

### ISSUE THREAD

**Issue by Boscop** [pyros2097/rust-embed#90]
How about adding optional compression support, like [include-flate](https://crates.io/crates/include-flate)?

**Comment by pyros2097** [comment]
Maybe some assets will benefit from compression. But we don't know what would be the best one to use. If its a web server maybe gzip will do good. And most of the image assets don't need to be compressed at all. I had used gzip in my go-embed tool. But do we want to inflate it one reading the file?

**Comment by Boscop** [comment]
I think it makes sense to support decompressing on reading.
E.g. not all rust-embed use cases are servers, some might be e.g. games bundling assets like textures / 3d models etc.
Servers like actix take uncompressed assets and compress them before serving.
So decompressing on reading would work for both.

**Comment by Mcat12** [comment]
A separate crate could build upon rust-embed to add this functionality. Does it need to be in this crate?

**Comment by Boscop** [comment]
@Mcat12 The separate crate would need to pre-process files that are embedded by rust-embed, so rust-embed would need to allow custom pre-processing!

**Comment by SirWindfield** [comment]
I mean, features are made for this kind of stuff. It would basically mean replacing the current `include_str!` macro call with the one from the crate above. I don't see anything wrong with providing this behind a flag that people can toggle if they want to.

**Comment by pyros2097** [comment]
@Boscop added in v5.3.0

**Comment by Boscop** [comment]
@pyros2097 Thanks!
