### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by paolobarbolini** [pyros2097/rust-embed#94]
It would be nice to release a new version now that rust-embed got updated to use syn 1.x so that downstream users can get rid of syn 0.11 from their crate graph.

**Comment by pyros2097** [comment]
@paolobarbolini sure will do

**Comment by pyros2097** [comment]
/remind me to release a new version Today at 10:00 PM

**Comment by pyros2097** [comment]
Done. Thanks @paolobarbolini .

**Comment by pyros2097** [comment]
Ohh shiz... I thought cargo publish succeeded. Will do it tonight again.

**Comment by pyros2097** [comment]
Wooh... Finally done. Caught a cold the past few days. 🤧
